services:
  manager:
    build: .
    command: ["./manager-exe"]
    ports:
      - "57107:57107"
    environment:
      - ENV=production
      - WORKERS_COUNT=1
    depends_on:
      - worker

  worker:
    build: .
    command: ["./worker-exe"]
    environment:
      - ENV=production
      - MANAGER_URL=http://manager:57107
      - PORT=57107